# 区块链系统配置文件

# 网络配置
network:
  port: 26656
  host: "0.0.0.0"
  max_peers: 50
  private_key_path: "./private_key.pem"  # 私钥文件路径（可选，留空则自动生成）
  bootstrap_peers:
    # DHT bootstrap 节点列表，格式为多地址格式
    # - "/ip4/192.168.1.100/tcp/26656/p2p/QmYyQSo1c1Ym7orWxLYvCrM2EmxFTANf8wXmmE7DWjhx5N"
    # - "/ip4/192.168.1.101/tcp/26656/p2p/QmYyQSo1c1Ym7orWxLYvCrM2EmxFTANf8wXmmE7DWjhx5N"

# 共识配置
consensus:
  algorithm: "dpos"
  validators_count: 21
  block_time: 2000  # 2秒
  round_blocks: 21  # 每轮21个区块
  min_stake: 1000000  # 最小质押量
  voting_period: 86400  # 投票周期24小时

# 存储配置
storage:
  data_dir: "./data"
  max_size: 1073741824  # 1GB
  cache_size: 1000
  compression: true

# 执行配置
execution:
  max_threads: 8
  batch_size: 100
  timeout: 5000 